# Generated by Django 4.1.6 on 2023-02-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_budjet_user_remove_category_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
